// Class: ReadBDT_Xgrad_d3_N020
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_Xgrad_d3_N020
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/03       [400899]
Creator        : ctarrico
Date           : Sat Nov  9 11:44:05 2024
Host           : Linux cmsbuild116.cern.ch 4.18.0-477.27.2.el8_8.x86_64 #1 SMP Fri Sep 29 08:21:01 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /eos/home-c/ctarrico/VZG_MVA
Training events: 301000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NTrees: "20" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 19
ptJ1                          ptJ1                          ptJ1                          ptJ1                                                            'D'    [30.0000286102,245.095977783]
ptGamma                       ptGamma                       ptGamma                       ptGamma                                                         'D'    [20.0000629425,1316.45935059]
mllPh                         mllPh                         mllPh                         mllPh                                                           'D'    [29.490228653,2484.76904297]
deltaR_L0Gamma                deltaR_L0Gamma                deltaR_L0Gamma                deltaR_L0Gamma                                                  'D'    [8.54528771015e-05,5.33769798279]
deltaR_L1Gamma                deltaR_L1Gamma                deltaR_L1Gamma                deltaR_L1Gamma                                                  'D'    [0.000365020416211,5.49829769135]
deltaR_J0Gamma                deltaR_J0Gamma                deltaR_J0Gamma                deltaR_J0Gamma                                                  'D'    [0.400481134653,7.20972824097]
deltaR_J1Gamma                deltaR_J1Gamma                deltaR_J1Gamma                deltaR_J1Gamma                                                  'D'    [0.400105714798,7.33719491959]
recoVMass                     recoVMass                     recoVMass                     recoVMass                                                       'D'    [50.0002479553,119.999893188]
FWMT1                         FWMT1                         FWMT1                         FWMT1                                                           'D'    [-0.622907400131,2.41034007072]
FWMT2                         FWMT2                         FWMT2                         FWMT2                                                           'D'    [-0.595023155212,2.2835624218]
FWMT4                         FWMT4                         FWMT4                         FWMT4                                                           'D'    [-0.568128883839,2.02185225487]
dRLG                          dRLG                          dRLG                          dRLG                                                            'D'    [8.54528771015e-05,5.12521219254]
J0Girth                       J0Girth                       J0Girth                       J0Girth                                                         'D'    [0.00234631914645,0.371182918549]
J1Girth                       J1Girth                       J1Girth                       J1Girth                                                         'D'    [0.00294950581156,0.419380605221]
J1DeepProb_g                  J1DeepProb_g                  J1DeepProb_g                  J1DeepProb_g                                                    'D'    [3.61452975994e-07,0.950619637966]
J0DeepProb_uds                J0DeepProb_uds                J0DeepProb_uds                J0DeepProb_uds                                                  'D'    [3.06260794503e-08,0.863481581211]
sqrt((ptJ0+ptJ1*cos(dPhiJJ))*(ptJ0+ptJ1*cos(dPhiJJ))+(ptJ1*sin(dPhiJJ))*(ptJ1*sin(dPhiJJ))) vectSumJpt                                                                                  vectSumJpt                                                                                  vectSumJpt                                                                                  D                                                                                               'F'    [0.0698894709349,755.889465332]
fabs(etaJ0-etaJ1)             dEtaJJ                        dEtaJJ                        dEtaJJ                        D                                 'F'    [1.28149986267e-06,2.79307150841]
fabs((etaG-(etaL0+etaL1)/2))  ZepCorr_G                     ZepCorr_G                     ZepCorr_G                     D                                 'F'    [2.98023223877e-07,4.64294147491]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_Xgrad_d3_N020Node

#ifndef BDT_Xgrad_d3_N020Node__def
#define BDT_Xgrad_d3_N020Node__def

class BDT_Xgrad_d3_N020Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_Xgrad_d3_N020Node ( BDT_Xgrad_d3_N020Node* left,BDT_Xgrad_d3_N020Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_Xgrad_d3_N020Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_Xgrad_d3_N020Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_Xgrad_d3_N020Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_Xgrad_d3_N020Node*   fLeft;     // pointer to the left daughter node
   BDT_Xgrad_d3_N020Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_Xgrad_d3_N020Node::~BDT_Xgrad_d3_N020Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_Xgrad_d3_N020Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_Xgrad_d3_N020Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_Xgrad_d3_N020 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_Xgrad_d3_N020( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_Xgrad_d3_N020" ),
        fNvars( 19 )
   {
      // the training input variables
      const char* inputVars[] = { "ptJ1", "ptGamma", "mllPh", "deltaR_L0Gamma", "deltaR_L1Gamma", "deltaR_J0Gamma", "deltaR_J1Gamma", "recoVMass", "FWMT1", "FWMT2", "FWMT4", "dRLG", "J0Girth", "J1Girth", "J1DeepProb_g", "J0DeepProb_uds", "sqrt((ptJ0+ptJ1*cos(dPhiJJ))*(ptJ0+ptJ1*cos(dPhiJJ))+(ptJ1*sin(dPhiJJ))*(ptJ1*sin(dPhiJJ)))", "fabs(etaJ0-etaJ1)", "fabs((etaG-(etaL0+etaL1)/2))" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';
      fType[15] = 'D';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_Xgrad_d3_N020() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[19];
   double fVmax[19];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[19];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_Xgrad_d3_N020Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_Xgrad_d3_N020::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_Xgrad_d3_N020Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_Xgrad_d3_N020Node*)current->GetRight();
         else current=(BDT_Xgrad_d3_N020Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT_Xgrad_d3_N020::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209087,-0.581826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460599,-0.0788024) , 
11, 0.789901, 1, 0, 0.261766,-0.238234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647821,0.295643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428831,-0.142337) , 
13, 0.0820224, 1, 0, 0.476984,-0.0230159) , 
0, 40.2427, 1, 0, 0.355202,-0.144798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866963,0.733927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729663,0.459327) , 
13, 0.143833, 1, 0, 0.828362,0.328362) , 
2, 146.408, 1, 0, 0.5,-7.16764e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447295,-0.0849597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684442,0.335659) , 
7, 67.7787, 1, 0, 0.650417,0.109017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445284,-0.138397) , 
7, 103.334, 1, 0, 0.612658,0.0784669) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309441,-0.331303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473129,-0.000256131) , 
7, 70.3175, 1, 0, 0.435626,-0.0303163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266687,-0.446017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304928,-0.376847) , 
15, 0.192169, 1, 0, 0.285761,-0.170305) , 
7, 103.333, 1, 0, 0.408076,-0.0560502) , 
12, 0.0901646, 1, 0, 0.5,0.00439178)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0305754,-0.727561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712551,0.752385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106642,-0.577461) , 
11, 0.109672, 1, 0, 0.419078,0.0510992) , 
11, 0.0465714, 1, 0, 0.303162,-0.0452899) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641437,0.0866844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490712,-0.167589) , 
5, 2.99501, 1, 0, 0.595731,0.00323077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822319,0.306095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668855,0.0548551) , 
14, 0.721803, 1, 0, 0.780789,0.0800623) , 
0, 39.5805, 1, 0, 0.693528,0.0438338) , 
11, 0.488193, 1, 0, 0.5,-0.000350202)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386742,-0.263432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426473,0.0508292) , 
2, 91.038, 1, 0, 0.414134,-0.0152835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840208,0.202096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77386,0.0632404) , 
6, 2.35507, 1, 0, 0.807989,0.0392203) , 
11, 0.9763, 1, 0, 0.576433,0.00717634) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542058,0.0151812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388633,-0.15327) , 
7, 96.67, 1, 0, 0.48147,-0.0151943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218109,-0.285435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664959,-0.0877445) , 
11, 1.16252, 1, 0, 0.353476,-0.0643668) , 
14, 0.494139, 1, 0, 0.403222,-0.0452552) , 
17, 0.798021, 1, 0, 0.5,-0.0159602)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416771,-0.113149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620819,0.0545644) , 
16, 72.0893, 1, 0, 0.535887,-0.00481539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625418,0.158543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491556,0.0160448) , 
14, 0.582502, 1, 0, 0.569835,0.0277175) , 
8, 0.238649, 1, 0, 0.550709,0.00938858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294435,-0.223074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248916,-0.138744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460404,0.0245616) , 
4, 1.73584, 1, 0, 0.344715,-0.017071) , 
8, -0.18853, 1, 0, 0.327645,-0.0331995) , 
13, 0.16159, 1, 0, 0.5,-0.000292938)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584415,0.158591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00843326,-0.713667) , 
11, 0.124552, 1, 0, 0.279978,-0.0572084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38812,0.0710967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798741,-0.11395) , 
2, 148.526, 1, 0, 0.506845,0.00663699) , 
2, 90.4597, 1, 0, 0.465119,-0.00510547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727789,0.141662) , 
1, 81.7362, 1, 0, 0.5,6.24294e-05)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0305756,-0.448224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742447,0.11022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218943,-0.220296) , 
11, 0.0936102, 1, 0, 0.519353,0.00133346) , 
11, 0.0465709, 1, 0, 0.343009,-0.0265322) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708801,0.0276943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575061,0.146563) , 
12, 0.0901633, 1, 0, 0.660595,0.0210311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385876,0.0452876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545162,-0.113018) , 
3, 2.18456, 1, 0, 0.465096,-0.011584) , 
12, 0.125292, 1, 0, 0.609089,0.0124384) , 
11, 0.244139, 1, 0, 0.5,-0.00353901)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304722,-0.198687) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711066,0.143546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497268,-0.00644793) , 
14, 0.271606, 1, 0, 0.527934,0.0032987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269118,-0.189488) , 
7, 114.286, 1, 0, 0.51311,0.000374108) , 
7, 60.0002, 1, 0, 0.5,-0.00273884)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546512,0.032253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682906,0.135265) , 
15, 0.287827, 1, 0, 0.615609,0.0199639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45497,-0.0651987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44113,0.0424309) , 
5, 2.99267, 1, 0, 0.447415,-0.00145482) , 
5, 2.57792, 1, 0, 0.537871,0.0100644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273809,-0.23277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362046,-0.0606762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.773269,0.086932) , 
2, 132.801, 1, 0, 0.488728,-0.00307301) , 
16, 36.0768, 1, 0, 0.453373,-0.0121398) , 
6, 2.71247, 1, 0, 0.5,0.000112732)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387006,0.101447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498586,-0.0526573) , 
3, 2.79598, 1, 0, 0.411261,0.0169294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217023,-0.160367) , 
17, 1.72905, 1, 0, 0.388765,0.0107789) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561135,-0.215656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514716,-0.22221) , 
17, 0.526943, 1, 0, 0.538424,-0.0522436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584471,-0.0597914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798596,0.176655) , 
0, 59.7525, 1, 0, 0.648245,0.000133619) , 
7, 76.667, 1, 0, 0.623888,-0.0114833) , 
0, 40.2427, 1, 0, 0.5,0.00024677)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562169,0.162166) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252004,-0.255706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464522,-0.0651175) , 
16, 61.0415, 1, 0, 0.386607,-0.0326267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611126,-0.0294422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419681,0.0650371) , 
12, 0.0901646, 1, 0, 0.5198,0.00431831) , 
15, 0.119439, 1, 0, 0.495493,-0.00242387) , 
15, 0.0411182, 1, 0, 0.5,0.000455965)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65817,0.0515157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644689,0.127579) , 
7, 86.6698, 1, 0, 0.650948,0.0252935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526762,-0.0269263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363162,0.0725158) , 
12, 0.132143, 1, 0, 0.489856,-0.000856334) , 
10, -0.213533, 1, 0, 0.509095,0.00226662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355575,-0.142944) , 
5, 3.96723, 1, 0, 0.5,5.22682e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322423,-0.082464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592076,0.055849) , 
4, 1.03756, 1, 0, 0.512903,0.0053309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265457,-0.191277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434528,-0.0568145) , 
3, 1.00817, 1, 0, 0.36488,-0.0235286) , 
10, 0.0485333, 1, 0, 0.437412,-0.00938735) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309318,-0.18961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503042,0.0201808) , 
16, 20.6356, 1, 0, 0.482275,-0.000278112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739789,0.135238) , 
16, 144.036, 1, 0, 0.536471,0.00558591) , 
15, 0.205591, 1, 0, 0.5,7.3118e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365668,-0.128319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308881,0.321438) , 
2, 93.6143, 1, 0, 0.339394,0.0127109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607499,0.00304455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326815,-0.11105) , 
13, 0.183072, 1, 0, 0.577617,-0.00253037) , 
3, 0.762602, 1, 0, 0.508235,0.00190864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38776,-0.0972127) , 
14, 0.860084, 1, 0, 0.5,0.000123084)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590027,-0.158166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778654,-0.0273046) , 
3, 1.25, 1, 0, 0.70498,-0.0166777) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494781,0.0219899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467976,-0.149162) , 
7, 95.7143, 1, 0, 0.490535,-0.00118404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410237,0.212024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286789,0.00855119) , 
7, 108.095, 1, 0, 0.328266,0.0190663) , 
7, 103.333, 1, 0, 0.46051,0.00256286) , 
13, 0.0822697, 1, 0, 0.5,-0.000545099)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469333,-0.0207667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668341,0.133848) , 
0, 37.6682, 1, 0, 0.58222,0.0164827) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524952,-0.0202628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312369,0.0499517) , 
13, 0.16159, 1, 0, 0.475383,-0.00095593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604691,-0.113816) , 
15, 0.699009, 1, 0, 0.485206,-0.00280267) , 
9, -0.183797, 1, 0, 0.5,0.000138303)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490735,0.0919875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705841,0.015125) , 
0, 38.8306, 1, 0, 0.621793,0.0114054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456009,-0.127177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42977,0.00848812) , 
6, 2.5843, 1, 0, 0.444014,-0.0159856) , 
7, 100, 1, 0, 0.580112,0.00498344) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209855,-0.228597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252342,0.0782741) , 
2, 96.2792, 1, 0, 0.226236,-0.0246343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603761,0.0691824) , 
2, 129.675, 1, 0, 0.360482,-0.00831445) , 
13, 0.14176, 1, 0, 0.5,0.000132909)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0305756,-0.300913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731696,0.167029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103967,-0.0271288) , 
11, 0.103018, 1, 0, 0.519353,0.0363271) , 
11, 0.0465709, 1, 0, 0.343009,0.0118092) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.014846,-0.778286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743178,0.109521) , 
2, 97.4306, 1, 0, 0.555579,-0.0133617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.880444,0.0947038) , 
1, 81.7362, 1, 0, 0.609089,-0.00846419) , 
11, 0.244139, 1, 0, 0.5,-0.000152383)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383478,-0.0118977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0180543,-0.560087) , 
11, 0.464925, 1, 0, 0.326979,-0.0129457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0872423,-0.341211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720354,0.312297) , 
11, 0.116431, 1, 0, 0.40542,0.0331608) , 
2, 97.8207, 1, 0, 0.360587,0.00680866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656191,-0.153261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819563,-0.138075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.879761,-0.0601006) , 
8, -0.0659099, 1, 0, 0.851818,-0.0192329) , 
2, 170.403, 1, 0, 0.775897,-0.0295045) , 
11, 1.22035, 1, 0, 0.5,-0.00538108)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599876,0.0486493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.037938,-0.346406) , 
11, 0.129887, 1, 0, 0.32689,-0.00731984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474173,0.205031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251158,-0.0421612) , 
13, 0.149456, 1, 0, 0.395688,0.0274846) , 
2, 101.868, 1, 0, 0.355202,0.0070031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826829,-0.18072) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85163,0.00376097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806443,-0.091271) , 
7, 86.6654, 1, 0, 0.829121,-0.0102198) , 
11, 1.70904, 1, 0, 0.828362,-0.0174231) , 
2, 146.408, 1, 0, 0.5,-0.000471873)    );
   return;
};

// Clean up
inline void ReadBDT_Xgrad_d3_N020::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_Xgrad_d3_N020::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
