// Class: ReadBDT_Xgrad_d4_N030
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_Xgrad_d4_N030
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/03       [400899]
Creator        : ctarrico
Date           : Sat Nov  9 11:52:45 2024
Host           : Linux cmsbuild116.cern.ch 4.18.0-477.27.2.el8_8.x86_64 #1 SMP Fri Sep 29 08:21:01 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /eos/home-c/ctarrico/VZG_MVA
Training events: 301000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NTrees: "30" [Number of trees in the forest]
MaxDepth: "4" [Max depth of the decision tree allowed]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 19
ptJ1                          ptJ1                          ptJ1                          ptJ1                                                            'D'    [30.0000286102,245.095977783]
ptGamma                       ptGamma                       ptGamma                       ptGamma                                                         'D'    [20.0000629425,1316.45935059]
mllPh                         mllPh                         mllPh                         mllPh                                                           'D'    [29.490228653,2484.76904297]
deltaR_L0Gamma                deltaR_L0Gamma                deltaR_L0Gamma                deltaR_L0Gamma                                                  'D'    [8.54528771015e-05,5.33769798279]
deltaR_L1Gamma                deltaR_L1Gamma                deltaR_L1Gamma                deltaR_L1Gamma                                                  'D'    [0.000365020416211,5.49829769135]
deltaR_J0Gamma                deltaR_J0Gamma                deltaR_J0Gamma                deltaR_J0Gamma                                                  'D'    [0.400481134653,7.20972824097]
deltaR_J1Gamma                deltaR_J1Gamma                deltaR_J1Gamma                deltaR_J1Gamma                                                  'D'    [0.400105714798,7.33719491959]
recoVMass                     recoVMass                     recoVMass                     recoVMass                                                       'D'    [50.0002479553,119.999893188]
FWMT1                         FWMT1                         FWMT1                         FWMT1                                                           'D'    [-0.622907400131,2.41034007072]
FWMT2                         FWMT2                         FWMT2                         FWMT2                                                           'D'    [-0.595023155212,2.2835624218]
FWMT4                         FWMT4                         FWMT4                         FWMT4                                                           'D'    [-0.568128883839,2.02185225487]
dRLG                          dRLG                          dRLG                          dRLG                                                            'D'    [8.54528771015e-05,5.12521219254]
J0Girth                       J0Girth                       J0Girth                       J0Girth                                                         'D'    [0.00234631914645,0.371182918549]
J1Girth                       J1Girth                       J1Girth                       J1Girth                                                         'D'    [0.00294950581156,0.419380605221]
J1DeepProb_g                  J1DeepProb_g                  J1DeepProb_g                  J1DeepProb_g                                                    'D'    [3.61452975994e-07,0.950619637966]
J0DeepProb_uds                J0DeepProb_uds                J0DeepProb_uds                J0DeepProb_uds                                                  'D'    [3.06260794503e-08,0.863481581211]
sqrt((ptJ0+ptJ1*cos(dPhiJJ))*(ptJ0+ptJ1*cos(dPhiJJ))+(ptJ1*sin(dPhiJJ))*(ptJ1*sin(dPhiJJ))) vectSumJpt                                                                                  vectSumJpt                                                                                  vectSumJpt                                                                                  D                                                                                               'F'    [0.0698894709349,755.889465332]
fabs(etaJ0-etaJ1)             dEtaJJ                        dEtaJJ                        dEtaJJ                        D                                 'F'    [1.28149986267e-06,2.79307150841]
fabs((etaG-(etaL0+etaL1)/2))  ZepCorr_G                     ZepCorr_G                     ZepCorr_G                     D                                 'F'    [2.98023223877e-07,4.64294147491]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_Xgrad_d4_N030Node

#ifndef BDT_Xgrad_d4_N030Node__def
#define BDT_Xgrad_d4_N030Node__def

class BDT_Xgrad_d4_N030Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_Xgrad_d4_N030Node ( BDT_Xgrad_d4_N030Node* left,BDT_Xgrad_d4_N030Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_Xgrad_d4_N030Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_Xgrad_d4_N030Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_Xgrad_d4_N030Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_Xgrad_d4_N030Node*   fLeft;     // pointer to the left daughter node
   BDT_Xgrad_d4_N030Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_Xgrad_d4_N030Node::~BDT_Xgrad_d4_N030Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_Xgrad_d4_N030Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_Xgrad_d4_N030Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_Xgrad_d4_N030 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_Xgrad_d4_N030( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_Xgrad_d4_N030" ),
        fNvars( 19 )
   {
      // the training input variables
      const char* inputVars[] = { "ptJ1", "ptGamma", "mllPh", "deltaR_L0Gamma", "deltaR_L1Gamma", "deltaR_J0Gamma", "deltaR_J1Gamma", "recoVMass", "FWMT1", "FWMT2", "FWMT4", "dRLG", "J0Girth", "J1Girth", "J1DeepProb_g", "J0DeepProb_uds", "sqrt((ptJ0+ptJ1*cos(dPhiJJ))*(ptJ0+ptJ1*cos(dPhiJJ))+(ptJ1*sin(dPhiJJ))*(ptJ1*sin(dPhiJJ)))", "fabs(etaJ0-etaJ1)", "fabs((etaG-(etaL0+etaL1)/2))" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';
      fType[15] = 'D';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_Xgrad_d4_N030() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[19];
   double fVmax[19];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[19];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_Xgrad_d4_N030Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_Xgrad_d4_N030::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_Xgrad_d4_N030Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_Xgrad_d4_N030Node*)current->GetRight();
         else current=(BDT_Xgrad_d4_N030Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT_Xgrad_d4_N030::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275752,-0.448495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119044,-0.761912) , 
11, 0.112914, 1, 0, 0.209087,-0.290913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460599,-0.0788024) , 
11, 0.789901, 1, 0, 0.261766,-0.238234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647821,0.295643) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382366,-0.235267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579787,0.159573) , 
11, 0.619588, 1, 0, 0.428831,-0.0711685) , 
13, 0.0820224, 1, 0, 0.476984,-0.0230159) , 
0, 40.2427, 1, 0, 0.355202,-0.144798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866963,0.733927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729663,0.459327) , 
13, 0.143833, 1, 0, 0.828362,0.328362) , 
2, 146.408, 1, 0, 0.5,-7.16764e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447295,-0.0813388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768677,0.476012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58445,0.171632) , 
14, 0.588479, 1, 0, 0.684442,0.131661) , 
7, 67.7787, 1, 0, 0.650417,0.10814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445284,-0.13832) , 
7, 103.334, 1, 0, 0.612658,0.0779138) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286086,-0.417807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334051,-0.245282) , 
8, 0.0959652, 1, 0, 0.309441,-0.13141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652842,0.228733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408745,-0.0903451) , 
13, 0.1021, 1, 0, 0.473129,-0.00321997) , 
7, 70.3175, 1, 0, 0.435626,-0.0325897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266687,-0.452229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304928,-0.394141) , 
15, 0.192169, 1, 0, 0.285761,-0.173982) , 
7, 103.333, 1, 0, 0.408076,-0.0585816) , 
12, 0.0901646, 1, 0, 0.5,0.00274922)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.197654,-0.243565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304192,-0.0146871) , 
8, 0.248042, 1, 0, 0.245676,-0.0516851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656801,0.0984161) , 
11, 0.488867, 1, 0, 0.456243,-0.0060714) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323738,-0.0987144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698072,0.134597) , 
11, 0.431117, 1, 0, 0.518567,0.00622478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637423,0.338118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798431,0.201651) , 
11, 0.223084, 1, 0, 0.739043,0.0919232) , 
7, 76.6673, 1, 0, 0.660045,0.0612171) , 
16, 72.0527, 1, 0, 0.576433,0.0336112) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304626,-0.04798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00552436,-0.767311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623215,0.424066) , 
2, 96.7226, 1, 0, 0.222273,-0.109915) , 
11, 0.110923, 1, 0, 0.262877,-0.0649578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584148,-0.0839188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.771787,0.11851) , 
16, 66.4482, 1, 0, 0.702086,0.0128577) , 
11, 1.16252, 1, 0, 0.403222,-0.0400925) , 
17, 0.798021, 1, 0, 0.5,0.00108784)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770895,0.230368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550098,0.0908624) , 
5, 2.57601, 1, 0, 0.698555,0.0544904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437167,0.0995557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637567,-0.0591726) , 
11, 0.244139, 1, 0, 0.550325,0.0061647) , 
6, 1.97418, 1, 0, 0.592025,0.0197599) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344647,-0.237314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37972,-0.0768448) , 
8, 0.0899123, 1, 0, 0.360985,-0.0524188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63494,0.0712953) , 
0, 50.4854, 1, 0, 0.450082,-0.0273132) , 
7, 96.6667, 1, 0, 0.550709,0.00605802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43116,-0.0513089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213973,-0.329309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293806,-0.15426) , 
8, -0.0441485, 1, 0, 0.261497,-0.0726528) , 
10, 0.0244344, 1, 0, 0.327645,-0.0514204) , 
13, 0.16159, 1, 0, 0.5,-0.0070085)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.141047,-0.488319) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743106,0.779647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618303,0.50238) , 
11, 0.0871812, 1, 0, 0.698413,0.2569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0201624,-0.785294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719275,0.3057) , 
2, 97.8207, 1, 0, 0.320543,-0.0594599) , 
11, 0.113536, 1, 0, 0.439911,0.0404772) , 
11, 0.0581932, 1, 0, 0.360587,-0.0159431) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85239,0.0979528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75521,0.216655) , 
12, 0.0901632, 1, 0, 0.819092,0.0427889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640558,-0.0215921) , 
12, 0.125292, 1, 0, 0.775897,0.0304685) , 
11, 1.22035, 1, 0, 0.5,-0.000363512)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682699,0.111814) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436177,-0.0460666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533318,-0.22354) , 
3, 2.79598, 1, 0, 0.454676,-0.0204394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711853,0.0729644) , 
1, 81.7362, 1, 0, 0.489183,-0.0153283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222562,-0.292427) , 
17, 1.72904, 1, 0, 0.470341,-0.0190843) , 
14, 0.271606, 1, 0, 0.5,-0.0127889)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57387,0.443961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679493,0.068545) , 
11, 0.0720247, 1, 0, 0.631156,0.0720113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0330753,-0.505501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00705001,-0.354479) , 
17, 0.798026, 1, 0, 0.0193521,-0.0491229) , 
11, 0.116295, 1, 0, 0.326979,0.0117857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0872423,-0.463319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76533,0.205436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649199,-0.12116) , 
17, 0.797611, 1, 0, 0.720354,0.0224767) , 
11, 0.116431, 1, 0, 0.40542,-0.0390684) , 
2, 97.8207, 1, 0, 0.360587,-0.0100028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790906,0.144536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810696,0.0967157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706771,-0.0444139) , 
5, 2.67023, 1, 0, 0.76866,0.00998941) , 
9, -0.0683031, 1, 0, 0.775897,0.0209053) , 
11, 1.22035, 1, 0, 0.5,0.000372574)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304722,-0.216399) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586566,0.173293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391136,-0.192935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445809,-0.0535505) , 
15, 0.110488, 1, 0, 0.417921,-0.0275663) , 
15, 0.03916, 1, 0, 0.447774,-0.015556) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647361,0.0032557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488863,0.111082) , 
12, 0.090491, 1, 0, 0.587264,0.0109072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289495,-0.113624) , 
17, 1.46304, 1, 0, 0.550608,0.00652523) , 
15, 0.205591, 1, 0, 0.51311,-0.00152654) , 
7, 60.0002, 1, 0, 0.5,-0.00454352)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514107,-0.217251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.839553,0.0323847) , 
11, 0.489451, 1, 0, 0.700818,-0.0145238) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519602,0.204391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575268,0.0675368) , 
15, 0.162813, 1, 0, 0.556998,0.0254953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462286,-0.0189473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316295,0.0885275) , 
7, 103.333, 1, 0, 0.434795,0.000242227) , 
14, 0.450426, 1, 0, 0.466851,0.00686651) , 
13, 0.0849177, 1, 0, 0.509095,0.00300438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355575,-0.186054) , 
5, 3.96723, 1, 0, 0.5,0.000299668)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456418,0.182109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228496,-0.139618) , 
4, 2.47045, 1, 0, 0.374242,0.0180567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262571,-0.126512) , 
1, 50.4314, 1, 0, 0.332778,0.0030233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326077,0.408809) , 
11, 0.39948, 1, 0, 0.331578,0.0149191) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307927,-0.0262941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542484,-0.291021) , 
11, 0.898656, 1, 0, 0.421099,-0.0451565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372564,-0.0641719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.801124,0.119405) , 
4, 1.30865, 1, 0, 0.584755,0.00973119) , 
1, 28.8195, 1, 0, 0.521228,-0.0115747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874314,0.148978) , 
1, 81.7362, 1, 0, 0.570758,-0.00594806) , 
3, 0.762602, 1, 0, 0.5,0.000225194)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640629,0.132555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179633,-0.135855) , 
11, 0.0885598, 1, 0, 0.369878,0.00474708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105424,-0.56966) , 
11, 0.619417, 1, 0, 0.337547,-0.00834876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0875195,-0.132861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697227,0.251148) , 
11, 0.474099, 1, 0, 0.384063,0.0360572) , 
2, 107.435, 1, 0, 0.355202,0.00850592) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758496,-0.127165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.878142,-0.0219902) , 
0, 39.5805, 1, 0, 0.828362,-0.0162994) , 
2, 146.408, 1, 0, 0.5,0.000914926)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473412,-0.00766578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292684,0.180646) , 
17, 1.40049, 1, 0, 0.44825,0.00329662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615445,-0.00282391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323236,-0.143978) , 
12, 0.115919, 1, 0, 0.499417,-0.0126485) , 
3, 2.10437, 1, 0, 0.46404,-0.00162387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.83061,0.102201) , 
11, 2.19657, 1, 0, 0.515283,0.00216022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274999,-0.160807) , 
7, 113.333, 1, 0, 0.5,-9.27027e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657374,-0.0458262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631591,0.130105) , 
5, 3.25094, 1, 0, 0.652751,-0.0019406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333251,-0.0549623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503097,0.0895377) , 
16, 29.5308, 1, 0, 0.467375,0.0135321) , 
12, 0.090491, 1, 0, 0.56006,0.00579609) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25782,-0.199138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422707,-0.0503062) , 
0, 32.3979, 1, 0, 0.369332,-0.0200239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238951,0.0623766) , 
7, 106.667, 1, 0, 0.334862,-0.0115838) , 
17, 1.19703, 1, 0, 0.508235,0.00179644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38776,-0.102055) , 
14, 0.860084, 1, 0, 0.5,0.000163311)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360934,0.207297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475391,0.0570249) , 
18, 0.217192, 1, 0, 0.444774,0.0203896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333489,-0.0721317) , 
5, 2.74746, 1, 0, 0.42374,0.0137003) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48436,0.0340155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625934,-0.105226) , 
16, 65.7641, 1, 0, 0.58553,-0.012388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783042,0.0849071) , 
0, 59.7528, 1, 0, 0.644704,-0.0044448) , 
0, 40.2429, 1, 0, 0.529212,0.00503913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264901,-0.242325) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604385,0.0107759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398727,-0.138808) , 
14, 0.449217, 1, 0, 0.472134,-0.0177198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62299,0.188193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351462,0.00325253) , 
13, 0.124468, 1, 0, 0.489343,0.0209677) , 
9, 0.362398, 1, 0, 0.479656,-0.000810095) , 
16, 36.0613, 1, 0, 0.443252,-0.00918595) , 
5, 2.99448, 1, 0, 0.5,0.000204956)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423345,-0.2646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699519,-0.05971) , 
11, 0.245212, 1, 0, 0.593922,-0.0260834) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362812,0.0800497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489788,-0.01579) , 
4, 1.9576, 1, 0, 0.41498,0.00822885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339257,-0.138419) , 
9, 0.642962, 1, 0, 0.403541,0.00263214) , 
13, 0.1021, 1, 0, 0.459071,-0.00574352) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631484,0.136857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538226,-0.00154568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368017,0.16064) , 
12, 0.117661, 1, 0, 0.502109,0.00686586) , 
17, 0.396986, 1, 0, 0.539593,0.0129811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620896,-0.0729603) , 
15, 0.699009, 1, 0, 0.553653,0.00835258) , 
15, 0.370064, 1, 0, 0.5,0.000356401)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548349,0.0458851) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5236,-0.0549445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250669,-0.238566) , 
13, 0.135753, 1, 0, 0.409662,-0.0268745) , 
6, 2.71247, 1, 0, 0.471535,-0.0105374) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410553,0.0770559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436071,-0.137422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712753,-0.0348446) , 
16, 70.2702, 1, 0, 0.621489,-0.0140269) , 
16, 36.0242, 1, 0, 0.575385,-0.00739971) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342446,-0.0556266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442721,0.0547899) , 
11, 0.0814317, 1, 0, 0.408852,0.00351388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810489,0.102745) , 
11, 1.70846, 1, 0, 0.480001,0.00764793) , 
6, 1.96091, 1, 0, 0.507923,0.00324293) , 
8, -0.334027, 1, 0, 0.5,0.000242475)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305243,0.145579) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235302,-0.268568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361213,0.0210707) , 
2, 88.1071, 1, 0, 0.318547,-0.0126447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333949,0.0870133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286042,-0.0943455) , 
1, 50.4311, 1, 0, 0.319428,0.00731051) , 
2, 91.038, 1, 0, 0.319117,0.000274115) , 
5, 2.01324, 1, 0, 0.316727,0.00448098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581363,-0.177968) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741403,0.0657507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826095,-0.0892559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737415,0.0239325) , 
5, 2.67023, 1, 0, 0.790714,-0.00878993) , 
15, 0.244319, 1, 0, 0.771317,0.00195889) , 
11, 1.15065, 1, 0, 0.731905,-0.00523702) , 
11, 0.732246, 1, 0, 0.5,0.000191145)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640442,-0.0233377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774818,0.0850074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641657,0.158278) , 
14, 0.476383, 1, 0, 0.71449,0.0226889) , 
7, 80.0034, 1, 0, 0.693006,0.0148655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48014,-0.0549381) , 
14, 0.769549, 1, 0, 0.642867,0.00838886) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432712,0.0710584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247374,-0.0631039) , 
12, 0.111239, 1, 0, 0.33004,0.000407824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728153,-0.0998124) , 
11, 0.976639, 1, 0, 0.483363,-0.00921864) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209946,-0.125545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271503,0.0341155) , 
15, 0.157967, 1, 0, 0.246698,-0.00455897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708674,0.0886717) , 
11, 1.16241, 1, 0, 0.387247,0.00552534) , 
14, 0.631578, 1, 0, 0.442435,-0.00294034) , 
12, 0.0726009, 1, 0, 0.5,0.000313461)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693511,0.0863501) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653204,0.00673461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456149,-0.0747492) , 
14, 0.497944, 1, 0, 0.535861,-0.00880138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513453,0.10547) , 
5, 3.59906, 1, 0, 0.533791,-0.00592509) , 
10, -0.196193, 1, 0, 0.555662,-0.00260453) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365891,0.261524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278575,-0.0100481) , 
4, 1.59385, 1, 0, 0.313525,0.0197855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45967,0.0366677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349435,-0.103139) , 
6, 2.58572, 1, 0, 0.407976,-0.00654583) , 
3, 2.03355, 1, 0, 0.355829,0.00799168) , 
12, 0.125292, 1, 0, 0.5,0.00034696)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629932,-0.0357359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518332,-0.110388) , 
6, 2.50963, 1, 0, 0.572302,-0.0150705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583607,0.0763903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451086,-0.0153198) , 
17, 0.662178, 1, 0, 0.504211,0.0042148) , 
17, 0.235687, 1, 0, 0.515678,0.000967214) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.300511,-0.186527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497814,-0.0508995) , 
16, 71.5283, 1, 0, 0.415079,-0.0226252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289893,0.0400471) , 
12, 0.109157, 1, 0, 0.367555,-0.011036) , 
7, 100, 1, 0, 0.480664,-0.00187012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64274,0.067562) , 
3, 3.05015, 1, 0, 0.5,0.000164201)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613666,0.0674452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48743,-0.151389) , 
6, 2.53786, 1, 0, 0.550473,-0.00871333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747458,-0.0520294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580224,0.0228962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50047,0.119186) , 
12, 0.0826358, 1, 0, 0.555058,0.011363) , 
14, 0.316873, 1, 0, 0.59061,0.00780547) , 
15, 0.205591, 1, 0, 0.581359,0.00399778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241981,0.0624771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495448,-0.104223) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339975,-0.0978804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4097,0.0157069) , 
7, 76.6672, 1, 0, 0.388541,-0.00380811) , 
10, -0.0953341, 1, 0, 0.417349,-0.00983244) , 
3, 0.254395, 1, 0, 0.380001,-0.00553846) , 
12, 0.107728, 1, 0, 0.5,0.00014465)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457518,0.0380053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.882166,-0.0434384) , 
2, 152.869, 1, 0, 0.593534,0.00293748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272514,-0.12371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684786,0.038776) , 
2, 129.675, 1, 0, 0.429776,-0.0104454) , 
13, 0.132901, 1, 0, 0.547809,-0.000799346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41984,-0.0258646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304244,0.116953) , 
12, 0.0999306, 1, 0, 0.35571,0.0113943) , 
13, 0.163478, 1, 0, 0.515983,0.00122086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257666,-0.0717665) , 
13, 0.20125, 1, 0, 0.5,0.000206859)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257078,-0.239909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437808,0.0776518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309438,-0.0710618) , 
6, 2.68182, 1, 0, 0.386948,0.00427345) , 
16, 15.4948, 1, 0, 0.350527,-0.0094914) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376526,-0.163391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531231,0.0238934) , 
15, 0.246709, 1, 0, 0.46439,-0.0112128) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.751758,0.130857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611564,-0.0152637) , 
17, 0.399011, 1, 0, 0.65422,0.00502905) , 
4, 1.83141, 1, 0, 0.55712,-0.00327886) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390252,0.22243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534164,0.0626334) , 
16, 100.298, 1, 0, 0.459264,0.0317507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581732,0.0458873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376567,-0.115981) , 
12, 0.0986858, 1, 0, 0.516749,-0.00170825) , 
15, 0.246619, 1, 0, 0.493096,0.0120587) , 
6, 2.92794, 1, 0, 0.534169,0.0022193) , 
16, 36.0613, 1, 0, 0.5,4.03754e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557911,0.00645736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459199,-0.0741423) , 
5, 3.62355, 1, 0, 0.548524,-0.000206419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510211,-0.149037) , 
7, 98.254, 1, 0, 0.544644,-0.00309899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442564,0.123351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232446,-0.104248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402689,0.0447029) , 
3, 1.73312, 1, 0, 0.314771,-0.00337008) , 
7, 108.889, 1, 0, 0.364414,0.00913772) , 
7, 103.333, 1, 0, 0.511244,-0.000831303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312212,0.092552) , 
12, 0.177983, 1, 0, 0.5,0.000231295)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489852,0.08239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542918,-0.0157147) , 
15, 0.12331, 1, 0, 0.530544,0.00155459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302945,-0.0955826) , 
12, 0.160419, 1, 0, 0.508362,-0.00046887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286518,-0.159427) , 
10, 0.541863, 1, 0, 0.491587,-0.00247347) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476553,-0.145201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648028,0.0422342) , 
18, 0.338588, 1, 0, 0.572358,-0.00776216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419436,0.00124564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534595,0.14285) , 
15, 0.36776, 1, 0, 0.478748,0.0149024) , 
10, 0.0312275, 1, 0, 0.517579,0.00550093) , 
8, 0.532615, 1, 0, 0.5,0.000107747)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614311,0.00135342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537347,-0.107608) , 
6, 1.60431, 1, 0, 0.593072,-0.00555367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5643,-0.0580249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485664,0.149951) , 
17, 0.532102, 1, 0, 0.516573,0.0146641) , 
6, 1.88768, 1, 0, 0.558742,0.00351934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646479,0.0872397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42982,0.00763216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415986,-0.0954282) , 
8, -0.0515715, 1, 0, 0.422165,-0.00977976) , 
14, 0.316873, 1, 0, 0.46348,-0.00498873) , 
6, 2.48271, 1, 0, 0.509095,-0.000914793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355575,0.087937) , 
5, 3.96723, 1, 0, 0.5,0.000141717)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486275,0.0300547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620157,-0.0975969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722795,-0.0172924) , 
15, 0.407024, 1, 0, 0.66579,-0.011748) , 
4, 1.04684, 1, 0, 0.606377,-0.00609841) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275955,-0.00608612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588297,0.127523) , 
2, 99.5121, 1, 0, 0.426572,0.0147004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383173,-0.128065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693135,0.025363) , 
16, 36.2157, 1, 0, 0.614618,-0.00300452) , 
3, 2.03346, 1, 0, 0.50906,0.00693399) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419618,-0.00761388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22901,-0.175611) , 
17, 1.05825, 1, 0, 0.359938,-0.0109671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338649,0.0922378) , 
5, 3.31922, 1, 0, 0.35509,-0.0045039) , 
10, 0.173337, 1, 0, 0.454824,0.00290503) , 
14, 0.407409, 1, 0, 0.5,0.00022124)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414959,-0.0563044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416754,0.116252) , 
10, -0.0598793, 1, 0, 0.416289,0.0136393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370967,-0.0613451) , 
4, 1.86095, 1, 0, 0.401227,0.00544028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679371,0.0374157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374892,-0.0115526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501055,-0.0999368) , 
18, 0.605451, 1, 0, 0.438512,-0.0122071) , 
13, 0.0924629, 1, 0, 0.493955,-0.00788308) , 
18, 0.31786, 1, 0, 0.455333,-0.00233383) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571796,-0.0636826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698475,0.122133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490853,-0.0314848) , 
7, 97.3016, 1, 0, 0.623509,0.0126796) , 
7, 76.6675, 1, 0, 0.61152,0.00646747) , 
3, 2.54181, 1, 0, 0.5,0.000183204)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432402,-0.0944414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441122,0.0310893) , 
18, 0.315848, 1, 0, 0.435996,-0.00739703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322227,0.173063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201899,0.0325811) , 
12, 0.0952437, 1, 0, 0.256806,0.017162) , 
13, 0.126224, 1, 0, 0.346836,0.00482282) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488088,0.044747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361388,-0.0933129) , 
5, 2.95953, 1, 0, 0.451692,0.00137316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49174,-0.0724222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463436,-0.215149) , 
18, 0.527915, 1, 0, 0.48072,-0.0257091) , 
18, 0.379014, 1, 0, 0.462373,-0.0085916) , 
3, 0.867633, 1, 0, 0.415801,-0.00318442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734056,0.101483) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629594,0.0333735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738987,-0.0792177) , 
4, 2.09514, 1, 0, 0.694493,-0.00668034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478775,0.067775) , 
13, 0.148746, 1, 0, 0.631993,0.000521229) , 
9, -0.0766833, 1, 0, 0.660234,0.00681296) , 
18, 0.663278, 1, 0, 0.5,0.000259337)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0305754,-0.436009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74342,0.177117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273231,0.00558679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448645,-0.237651) , 
1, 51.7883, 1, 0, 0.302875,-0.0054718) , 
11, 0.0908581, 1, 0, 0.435439,0.0109575) , 
11, 0.0465718, 1, 0, 0.338064,-0.0034099) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.851942,0.0347241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685564,-0.0462598) , 
13, 0.139417, 1, 0, 0.80262,0.000581696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623208,-0.00683507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709219,0.129894) , 
8, -0.0544666, 1, 0, 0.666309,0.0178566) , 
17, 0.931025, 1, 0, 0.758689,0.00614903) , 
11, 0.9763, 1, 0, 0.5,0.000270183)    );
   return;
};

// Clean up
inline void ReadBDT_Xgrad_d4_N030::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_Xgrad_d4_N030::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
