#include <VVXAnalysis/DataFormats/interface/Particle.h>
#include <VVXAnalysis/DataFormats/interface/Lepton.h>
#include <VVXAnalysis/DataFormats/interface/Photon.h>
#include <VVXAnalysis/DataFormats/interface/Jet.h>
#include <VVXAnalysis/DataFormats/interface/Electron.h>
#include <VVXAnalysis/DataFormats/interface/Boson.h>
#include <VVXAnalysis/DataFormats/interface/DiBoson.h>
#include <VVXAnalysis/DataFormats/interface/RegionsCounter.h>
#include <VVXAnalysis/DataFormats/interface/GenEventWeights.h>
#include <VVXAnalysis/DataFormats/interface/MELA.h>
